import localFont from "next/font/local";
import "./globals.css";  // Import global styles
import Header from "./components/Layout/Header.jsx";
import Footer from "./components/Layout/Footer.jsx";
import { ConfigProvider,theme  } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const geistSans = localFont({
  src: "../assets/fonts/Rajdhani.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/Rajdhani.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            // Mapping your custom variables to Ant Design tokens
            colorPrimary: '#7228e2',        // Primary color
            colorInfo: '#cc99ff',           // Info color
            colorBgBase: '#20132a',         // Base background color
            colorLink: '#cc99ff',           // Link color
            colorTextBase: '#ededed',       // Base text color
            colorError: '#ff4d4f',          // Error color
            colorWarning: '#faad14',        // Warning color
            colorSuccess: '#52c41a',        // Success color
            colorPrimaryHover: '#894bda',   // Primary hover color
            "wireframe": false,
          },
        }}
      >
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Header />
          <AntdRegistry>{children}</AntdRegistry>
          <Footer></Footer>
        </body>
      </ConfigProvider>
    </html>
  );
}
